// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB55rIDfFPAcIvDDr5m-EiaRAkZvCEM96c',
    appId: '1:317051483443:web:cf2fd5a70dc70c66adba46',
    messagingSenderId: '317051483443',
    projectId: 'meditrackrx-6138b',
    authDomain: 'meditrackrx-6138b.firebaseapp.com',
    storageBucket: 'meditrackrx-6138b.firebasestorage.app',
    measurementId: 'G-E5VNTGN98Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLfqdPnFsFtP1G6wTInQITVIyxTGaGmQ',
    appId: '1:317051483443:android:a16110f06d5330b6adba46',
    messagingSenderId: '317051483443',
    projectId: 'meditrackrx-6138b',
    storageBucket: 'meditrackrx-6138b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEdYKghD3_U8vqaJY6aIMfoCbjl_a0hg',
    appId: '1:317051483443:ios:a1b2aeb332897371adba46',
    messagingSenderId: '317051483443',
    projectId: 'meditrackrx-6138b',
    storageBucket: 'meditrackrx-6138b.firebasestorage.app',
    iosBundleId: 'com.example.meditrackrx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOEdYKghD3_U8vqaJY6aIMfoCbjl_a0hg',
    appId: '1:317051483443:ios:a1b2aeb332897371adba46',
    messagingSenderId: '317051483443',
    projectId: 'meditrackrx-6138b',
    storageBucket: 'meditrackrx-6138b.firebasestorage.app',
    iosBundleId: 'com.example.meditrackrx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB55rIDfFPAcIvDDr5m-EiaRAkZvCEM96c',
    appId: '1:317051483443:web:2e34ad8ca79f0976adba46',
    messagingSenderId: '317051483443',
    projectId: 'meditrackrx-6138b',
    authDomain: 'meditrackrx-6138b.firebaseapp.com',
    storageBucket: 'meditrackrx-6138b.firebasestorage.app',
    measurementId: 'G-93CLZ8KZFE',
  );
}
